name: Create Rotating 100-Config Subscriptions

on:
  schedule:
    - cron: '*/5 * * * *' # Run every 5 minutes
  workflow_dispatch:

jobs:
  create-chunks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Run script to create all rotating subscriptions
        run: python create_rotating_sub.py
      
      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          # اضافه کردن تمام فایل‌های مرتبط با این قابلیت برای همه کشورها
          git add subscription/*_100.txt subscription/*_shuffled.txt subscription/*_index.txt
          
          if git diff --staged --quiet; then
            echo "✅ No new rotating subs generated. Skipping commit."
          else
            git commit -m "Update rotating 100-config subscriptions for all countries"
            git push
          fi
