# نام ورک‌فلو مخصوص برنچ توسعه (نسخه ساده شده)
name: Develop Proxy Pipeline

on:
  # این ورک‌فلو فقط زمانی اجرا می‌شود که تغییری به برنچ develop ارسال شود
  push:
    branches:
      - develop
  # امکان اجرای دستی را هم فراهم می‌کند
  workflow_dispatch:

# تضمین می‌کند که فقط یک نمونه از این ربات در هر لحظه در حال اجرا باشد
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  #----------------------------------------------------
  # مرحله ۱: آماده‌سازی و بسته‌بندی کارها
  #----------------------------------------------------
  prepare-work:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install Dependencies
        run: pip install pyyaml httpx requests

      - name: Run Data Acquisition and Batching
        env:
          GH_PAT: "${{ secrets.GH_PAT }}"
        run: |
          python manage_sources.py
          python merge_configs.py
          python prepare_batches.py
      
      - name: Upload Batch Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: work-batches-develop
          path: ci_batches/

  #------------------------------------------------------------------
  # مرحله ۲: اجرای تست‌های موازی (تست سرعت مستقیم)
  #------------------------------------------------------------------
  run-speed-tests:
    # --- تغییر: این جاب دیگر به تست زنده بودن وابسته نیست ---
    needs: prepare-work
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        batch_id: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
    
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install Dependencies
        run: pip install requests geoip2 pyyaml httpx

      - name: Download Prerequisite Tools (Xray, Hysteria2 & GeoIP)
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          wget -q https://github.com/P3TERX/GeoLite.mmdb/raw/download/GeoLite2-City.mmdb -O GeoLite2-City.mmdb
          wget -q -O xray.zip https://github.com/XTLS/Xray-core/releases/latest/download/Xray-linux-64.zip
          unzip -o -q xray.zip xray
          chmod +x xray
          wget -q https://github.com/apernet/hysteria/releases/latest/download/hysteria-linux-amd64 -O hysteria
          chmod +x hysteria
          echo "Xray, Hysteria2, and GeoIP are ready."
      
      # --- تغییر: این جاب دیگر آرتیفکت تست زنده بودن را دانلود نمی‌کند ---
      - name: Download Config Batch Artifact
        uses: actions/download-artifact@v4
        with:
          name: work-batches-develop
          path: ci_batches/
      
      - name: Run Speed Test on Assigned Batch
        run: |
          # --- تغییر: ورودی اسکریپت تست سرعت، فایل batch اصلی است ---
          CONFIG_FILE="ci_batches/batch_${{ matrix.batch_id }}.txt"
          DB_FILE="results_${{ matrix.batch_id }}.db"
          # اطمینان از وجود فایل قبل از اجرا
          if [ -f "$CONFIG_FILE" ]; then
            python test_worker.py --input "$CONFIG_FILE" --db-file "$DB_FILE"
          else
            echo "Batch file $CONFIG_FILE not found, skipping."
          fi

      - name: Upload Result Artifact
        uses: actions/upload-artifact@v4
        with:
          name: db-result-develop-${{ matrix.batch_id }}
          path: results_${{ matrix.batch_id }}.db
  
  #-------------------------------------------------------------
  # مرحله ۳: ادغام نتایج، ساخت خروجی‌ها و انتشار
  #-------------------------------------------------------------
  merge-and-publish:
    runs-on: ubuntu-latest
    needs: run-speed-tests
    if: success() || failure()
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install pyyaml jdatetime pytz

      - name: Download All Result Artifacts
        uses: actions/download-artifact@v4
        with:
          path: db_results/
          pattern: db-result-develop-*

      - name: Merge, Generate, and Finalize
        run: |
          python merge_databases.py --input-dir db_results/ --output-db aggregator_data.db
          python create_rotating_sub.py
          python generate_readme.py
      
      - name: Commit and Push Final Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action (Develop Pipeline)"
          git add .
          if ! git diff --staged --quiet; then
            git commit -m "feat(auto-dev): update proxy configurations and README"
            git pull --rebase
            git push
          else
            echo "No changes to commit."
          fi
