name: Find New Proxy Sources Daily

on:
  schedule:
    # هر روز در ساعت 00:00 UTC اجرا می‌شود
    - cron: '0 0 * * *'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  find-sources:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests

      - name: Run script to find new sources
        run: python find_sources.py
        env:
          GH_PAT: ${{ secrets.GH_PAT }}

      - name: Commit and push discovered sources
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          git add discovered_sources.txt crawled_urls.txt
          
          # اگر فایلی برای کامیت وجود داشت، ادامه بده
          if ! git diff --staged --quiet; then
            echo "Changes detected. Committing and pushing..."
            git commit -m "Update discovered sources and crawl state"
            
            # ۱. آخرین تغییرات را از سرور بکش
            git pull --rebase
            
            # ۲. حالا تغییرات خود را پوش کن
            git push
          else
            echo "✅ No new sources or state changes. Skipping commit."
          fi
