name: Maintain Final Database

on:
  schedule:
    # Runs once daily at 05:00 UTC
    - cron: '0 5 * * *'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  maintain-db:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        # We need the full history to get the database file
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          
      - name: Install Dependencies
        run: pip install pyyaml httpx requests geoip2

      - name: Download Cached Dependencies (Xray, GeoIP)
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release download deps/geoip-latest --repo ${{ github.repository }} --pattern '*.mmdb' --clobber
          LATEST_XRAY_TAG=$(gh release list --repo ${{ github.repository }} --limit 50 --json tagName --jq '.[] | select(.tagName | startswith("deps/xray-")) | .tagName' | head -n 1)
          if [ -z "$LATEST_XRAY_TAG" ]; then echo "::error::No cached Xray release found."; exit 1; fi
          gh release download "$LATEST_XRAY_TAG" --repo ${{ github.repository }} --pattern 'xray' --clobber
          chmod +x xray

      - name: Run Database Maintenance Script
        run: python maintain_db.py

      - name: Commit and Push Database Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action (Maintenance)"
          # Only add the database file itself
          git add aggregator_data.db
          if git diff --staged --quiet; then
            echo "No changes to the database. Skipping commit."
          else
            git commit -m "chore(db): perform daily maintenance"
            git push
          fi
