name: Merge Proxy Configs and Remove Duplicates

on:
  schedule:
    - cron: '0 * * * *' # Run every hour
  workflow_dispatch: # Allow manual trigger

jobs:
  merge-configs:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      # Install required Python packages
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      # Run Python script to merge configs and remove duplicates
      - name: Merge configs and remove duplicates
        run: python merge_configs.py

      # Commit and push the merged file
      - name: Commit merged file
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add merged_configs.txt
          git commit -m "Update merged proxy configs"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
