name: Merge and Extract Country-Specific Proxy Configs

on:
  schedule:
    - cron: '0 * * * *' # Run every hour
  workflow_dispatch: # Allow manual trigger

jobs:
  merge-and-extract:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests geoip2

      - name: Configure DNS
        run: |
          echo "nameserver 8.8.8.8" | sudo tee /etc/resolv.conf
          echo "nameserver 8.8.4.4" | sudo tee -a /etc/resolv.conf
          echo "nameserver 1.1.1.1" | sudo tee -a /etc/resolv.conf

      - name: Run merge_configs.py
        run: |
          python merge_configs.py
          echo "Total configs:"
          wc -l merged_configs.txt || echo "merged_configs.txt is empty"
          git add merged_configs.txt || echo "Failed to add merged_configs.txt"

      - name: Run exp_country.py
        env:
          MAXMIND_LICENSE_KEY: ${{ secrets.MAXMIND_LICENSE_KEY }}
        run: |
          python exp_country.py
          cat http_test.log || echo "No http_test.log found"
          ls subscription || echo "No files in subscription directory"
          git add subscription/*.txt http_test.log || echo "Failed to add subscription files or http_test.log"

      - name: Commit and push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git status
          git commit -m "Update merged_configs.txt, subscription files, and http_test.log" || echo "Nothing to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
