name: Telegram Scraper (Develop)

on:
  # این ورک‌فلو فقط زمانی اجرا می‌شود که تغییری به برنچ develop ارسال شود
  push:
    branches:
      - develop
  # امکان اجرای دستی را هم فراهم می‌کند
  workflow_dispatch:

jobs:
  collect:
    name: Collect from Telegram
    runs-on: ubuntu-latest
    
    # --- فقط روی برنچ develop اجرا شود ---
    if: github.ref == 'refs/heads/develop'

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          # --- مهم: مطمئن می‌شویم که برنچ develop را چک‌اوت می‌کنیم ---
          ref: 'develop'

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: pip install telethon

      - name: Run Telegram Scraper
        env:
          # --- خواندن سکرت‌ها و ارسال به اسکریپت ---
          TELEGRAM_API_ID: ${{ secrets.TELEGRAM_API_ID }}
          TELEGRAM_API_HASH: ${{ secrets.TELEGRAM_API_HASH }}
          TELEGRAM_SESSION: ${{ secrets.TELEGRAM_SESSION }}
        run: python telegram_scraper.py

      - name: Commit and Push Results to Develop Branch
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action (Telegram Dev)"
          # اضافه کردن فایل‌های خروجی
          git add telegram_direct_configs.txt telegram_source_links.txt
          
          if ! git diff --staged --quiet; then
            git commit -m "chore(data): update telegram sources [dev]"
            git pull --rebase origin develop
            git push origin develop
          else
            echo "No new data from Telegram to commit."
          fi
