name: Telegram Scraper (Develop)

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  scrape:
    name: Scrape Telegram Sources
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: pip install telethon

      - name: Run Telegram Scraper
        env:
          TELEGRAM_API_ID: ${{ secrets.TELEGRAM_API_ID }}
          TELEGRAM_API_HASH: ${{ secrets.TELEGRAM_API_HASH }}
          TELEGRAM_SESSION: ${{ secrets.TELEGRAM_SESSION }}
        run: python telegram_scraper.py

      - name: Commit and Push Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action (Telegram Scraper)"
          git add .
          
          if ! git diff --staged --quiet; then
            git commit -m "chore(data): update configs from telegram"
            git pull --rebase
            git push
          else
            echo "No new configs or sources from Telegram."
          fi
