name: Test Matrix Pipeline on Develop Branch

on:
  push:
    branches:
      - develop
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # JOB 1: Prepares the work batches for parallel workers
  prepare-work:
    runs-on: ubuntu-latest
    outputs:
      # We will output a JSON string array like "[0,1,2,3,4,5,6,7,8,9]"
      batch_matrix: ${{ steps.prep.outputs.batch_matrix }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install Dependencies
        run: pip install pyyaml

      - name: Create Batches and Generate Matrix
        id: prep
        run: |
          python prepare_batches.py
          # Generate the JSON array string for the matrix
          count=$(ls -1q ci_batches/ | wc -l)
          if [ "$count" -gt 0 ]; then
            matrix=$(seq 0 $(($count - 1)) | jq -c -s '.')
          else
            matrix="[]"
          fi
          echo "Generated Matrix: $matrix"
          echo "batch_matrix=$matrix" >> $GITHUB_OUTPUT
          
      - name: Upload Batch Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: work-batches
          path: ci_batches/

  # JOB 2: Runs tests in parallel using a matrix strategy
  run-tests:
    needs: prepare-work
    if: fromJson(needs.prepare-work.outputs.batch_matrix)[0] != null # Run only if batches were created
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # Directly use the JSON array string from the previous job
        batch_id: ${{ fromJson(needs.prepare-work.outputs.batch_matrix) }}
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install Dependencies
        run: pip install requests geoip2 pyyaml httpx

      - name: Download Cached Dependencies (Xray, GeoIP)
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release download deps/geoip-latest --repo ${{ github.repository }} --pattern '*.mmdb' --clobber
          LATEST_XRAY_TAG=$(gh release list --repo ${{ github.repository }} --limit 50 --json tagName --jq '.[] | select(.tagName | startswith("deps/xray-")) | .tagName' | head -n 1)
          if [ -z "$LATEST_XRAY_TAG" ]; then exit 1; fi
          gh release download "$LATEST_XRAY_TAG" --repo ${{ github.repository }} --pattern 'xray' --clobber
          chmod +x xray

      - name: Download Batch Artifacts
        uses: actions/download-artifact@v4
        with:
          name: work-batches
          path: ci_batches/
          
      - name: Run Tests on Assigned Batch
        run: |
          BATCH_FILE="ci_batches/batch_${{ matrix.batch_id }}.txt"
          CANDIDATES_FILE="candidates_${{ matrix.batch_id }}.txt"
          DB_FILE="results_${{ matrix.batch_id }}.db"

          echo "--- Worker ${{ matrix.batch_id }} processing $BATCH_FILE ---"
          
          python check_liveness.py --input $BATCH_FILE --output $CANDIDATES_FILE
          python exp_country.py --input $CANDIDATES_FILE --db-file $DB_FILE

      - name: Upload Result Artifact
        uses: actions/upload-artifact@v4
        with:
          name: db-result-${{ matrix.batch_id }}
          path: results_${{ matrix.batch_id }}.db

  # JOB 3: Merges all results and publishes the final output
  merge-results:
    runs-on: ubuntu-latest
    needs: run-tests
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install Dependencies
        run: pip install pyyaml jdatetime pytz

      - name: Download All Result Artifacts
        uses: actions/download-artifact@v4
        with:
          name: db-result-*
          path: db_results/

      - name: Merge, Generate, and Finalize
        run: |
          python merge_databases.py --input-dir db_results/ --output-db aggregator_data.db
          python create_rotating_sub.py
          python generate_readme.py

      - name: Commit and Push Final Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action (Matrix)"
          git add .
          if git diff --staged --quiet; then
            echo "No changes detected.";
          else
            git commit -m "feat: update data via matrix workflow"
            git push
          fi