name: Update US VPN List

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 * * * *'  # هر ساعت اجرا بشه
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout کردن مخزن
      - name: Checkout repository
        uses: actions/checkout@v4

      # نصب پایتون
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      # نصب وابستگی‌ها
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests geoip2

      # اجرای اسکریپت پایتون
      - name: Run Python Script
        run: python script.py
        env:
          MAXMIND_LICENSE_KEY: ${{ secrets.MAXMIND_LICENSE_KEY }}

      # آپلود فایل‌های خروجی به عنوان artifact
      - name: Upload output files
        uses: actions/upload-artifact@v4
        with:
          name: output-files
          path: |
            sub/us_only_sub.txt
            http_test.log

      # Commit و push فایل خروجی به مخزن
      - name: Commit output file
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add sub/us_only_sub.txt
          git commit -m "Update us_only_sub.txt" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: always()
