name: Update US VPN List

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 * * * *'  # هر ساعت اجرا بشه
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout کردن مخزن
      - name: Checkout repository
        uses: actions/checkout@v4

      # نصب پایتون
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      # نصب وابستگی‌ها
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests geoip2

      # اجرای اسکریپت پایتون
      - name: Run Python Script
        run: python script.py
        env:
          MAXMIND_LICENSE_KEY: ${{ secrets.MAXMIND_LICENSE_KEY }}
