name: Update All Proxy Subscriptions

on:
  schedule:
    # Runs every 3 hours
    - cron: '0 */3 * * *'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  update-all:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: pip install requests pyyaml httpx geoip2 jdatetime pytz

      - name: Download GeoIP Database
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release download deps/geoip-latest --repo ${{ github.repository }} --pattern '*.mmdb' --clobber

      - name: Run Main Pipeline
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          python manage_sources.py
          python merge_configs.py
          python check_liveness.py --output live_candidates.txt
          python exp_country.py --input live_candidates.txt
          python create_rotating_sub.py
          python generate_readme.py
          
      - name: Commit and Push Final Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          
          # Check if there are actual changes to commit
          if ! git diff --staged --quiet; then
            # Step 1: Commit the generated changes locally
            git commit -m "chore: data update"
            
            # Step 2: Pull remote changes and rebase our local commit on top
            git pull --rebase
            
            # Step 3: Push the final result
            git push
          else
            echo "No changes to commit."
          fi
