name: Update All Proxy Subscriptions

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  update-all:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Get current date
        id: date
        run: echo "TODAY=$(date -u +'%Y-%m-%d')" >> $GITHUB_OUTPUT

      - name: Cache GeoIP Database
        id: cache-geoip
        uses: actions/cache@v4
        with:
          path: GeoLite2-City.mmdb
          key: ${{ runner.os }}-geoip-${{ steps.date.outputs.TODAY }}
          restore-keys: |
            ${{ runner.os }}-geoip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests geoip2 jdatetime pytz

      - name: STEP 1 - Run All Python Scripts
        run: |
          # اطمینان حاصل شود که فایل .gitignore وجود دارد و قانون در آن هست
          echo "merged_configs.txt" >> .gitignore
          
          python find_sources.py
          python manage_sources.py
          python merge_configs.py
          
          if [ ! -f GeoLite2-City.mmdb ]; then
            python -c "from exp_country import download_geoip_database; download_geoip_database()"
          fi
          python exp_country.py
          
          python create_rotating_sub.py
          python generate_readme.py
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
          MAXMIND_LICENSE_KEY: ${{ secrets.MAXMIND_LICENSE_KEY }}

      - name: STEP 2 - Commit repository changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

          # --- دستور کلیدی و مهم ---
          # فایل حجیم را از ردیابی گیت حذف کن (اما خود فایل را نگه دار)
          git rm --cached merged_configs.txt || true

          # حالا بقیه تغییرات را اضافه کن
          git add .
          
          if git diff --staged --quiet; then
            echo "No repository changes to commit."
          else
            git commit -m "Update subscriptions and project files"
            git push
          fi
      
      - name: STEP 3 - Upload Merged Configs to Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          files: merged_configs.txt
          body: "آخرین لیست تجمیع‌شده کانفیگ‌ها. این فایل به صورت خودکار هر ساعت به‌روز می‌شود."
          prerelease: false
          make_latest: true
