name: Update External Dependencies

on:
  workflow_dispatch:
  schedule:
    # Run once daily at 03:00 UTC
    - cron: '0 3 * * *'

jobs:
  update-xray-package:
    name: Check and Cache Full Xray Package
    runs-on: ubuntu-latest
    steps:
      - name: Download and Extract Xray Package
        run: |
          wget -q -O xray.zip https://github.com/XTLS/Xray-core/releases/latest/download/Xray-linux-64.zip
          unzip -o -q xray.zip xray geoip.dat geosite.dat
          chmod +x ./xray

      - name: Get Xray Version
        id: xray_version
        run: echo "VERSION=$(./xray --version | head -n 1 | awk '{print $2}')" >> $GITHUB_OUTPUT

      - name: Create New Release if it does not exist
        uses: softprops/action-gh-release@v2
        with:
          tag_name: deps/xray-pkg-${{ steps.xray_version.outputs.VERSION }}
          name: "Xray Package v${{ steps.xray_version.outputs.VERSION }}"
          body: "Automated cache of Xray binary with geoip.dat and geosite.dat."
          files: |
            ./xray
            ./geoip.dat
            ./geosite.dat
