name: Update US VPN List

on:
  schedule:
    - cron: "0 */6 * * *"  # هر 6 ساعت
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests geoip2 pythonping
      - name: Download GeoLite2 database
        env:
          MAXMIND_LICENSE_KEY: ${{ secrets.MAXMIND_LICENSE_KEY }}
        run: |
          wget -q -O GeoLite2-City.tar.gz "https://download.maxmind.com/app/geoip_download?edition_id=GeoLite2-City&license_key=$MAXMIND_LICENSE_KEY&suffix=tar.gz"
          tar -xzf GeoLite2-City.tar.gz
          mv GeoLite2-City_*/GeoLite2-City.mmdb .
      - name: Run script
        run: python script.py
      - name: Upload log file
        uses: actions/upload-artifact@v4
        with:
          name: ping-test-log
          path: ping_test.log
      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add sub/us_only_sub.txt ip_cache.pkl ping_test.log
          git commit -m "Update US-only VPN list with ping test" || echo "No changes to commit"
          git push
